version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:management-alpine
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 3s
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:alpine
    healthcheck:
      test: redis-cli ping
      interval: 3s
    ports:
      - "6379:6379"

networks:
  default:
    name: ms_network
